version: '3.4'

services:
  sio.eventpublisher:
    image: ${DOCKER_REGISTRY-}sioeventpublisher
    build:
      context: .
      dockerfile: src/SIO.EventPublisher/Dockerfile
    depends_on: 
      - sio.eventpublisher.sql.projections
    external_links:
      - sio.sql.store
  sio.eventpublisher.sql.projections:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sio.eventpublisher.sql.projections
networks:    
  default:
    external:
        name: sio.network