version: '3.4'

services:
  sio.eventpublisher:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Store=Server=sio.sql.store;Initial Catalog=sio-store;User Id=sa;Password=1qaz-pl,
      - ConnectionStrings__Projection=Server=sio.eventpublisher.sql.projections;Initial Catalog=sio-api-projections;User Id=sa;Password=1qaz-pl,
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  sio.eventpublisher.sql.projections:
    environment:
      SA_PASSWORD: "1qaz-pl,"
      ACCEPT_EULA: "Y"
    ports:
      - "1450:1433"
    volumes:
      - /var/opt/mssql/data
