// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIO.Infrastructure.EntityFrameworkCore.DbContexts;

#nullable disable

namespace SIO.Migrations.Migrations.SIO.Projection
{
    [DbContext(typeof(SIOProjectionDbContext))]
    [Migration("20220113191838_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SIO.Domain.EventPublications.Projections.EventPublicationFailure", b =>
                {
                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventSubject")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Subject");

                    b.HasIndex("EventSubject");

                    b.ToTable("EventPublicationFailure", (string)null);
                });

            modelBuilder.Entity("SIO.Domain.EventPublications.Projections.EventPublicationQueue", b =>
                {
                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("EventSubject")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("PublicationDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Subject");

                    b.HasIndex("EventSubject");

                    b.ToTable("EventPublicationQueue", (string)null);
                });

            modelBuilder.Entity("SIO.Infrastructure.EntityFrameworkCore.Entities.ProjectionState", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("Name");

                    b.ToTable("ProjectionState", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
